### ISSUE TITLE
Adding old token fails with 1.2.0

### ISSUE THREAD

**Issue by okin** [k3s-io/k3s-ansible#529]
After upgrading k3s-ansible to 1.2.0 the upgrade playbook fails at `Add old token to server config`:

```
TASK [k3s.orchestration.k3s_upgrade : Add old token to server config] *********************************************************
fatal: [cp2.mynetwork.tld]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'. 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '.../collections/ansible_collections/k3s/orchestration/roles/k3s_upgrade/tasks/main.yml': line 63, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        # If token is not defined, use the old token\n        - name: Add old token to server config\n          ^ here\n"}
```

My setup for this is that I do not define a token anywhere and only use what is automatically set.
Running the same config with version 1.1.1 (of the collection) works.
